#!/usr/bin/env python3
from discord.ext import commands
import aiosqlite
from aioosuapi import aioosuapi
import discord
import os

from suwako.modules import first_run
from suwako.modules import permissions
from suwako.manifest import VERSION
from suwako.manifest import CONTRIBUTORS

from suwako.modules.connections import bot_token as bot_token
from suwako.modules.connections import osu_api_key as osu_api_key
from suwako.modules.storage_management import database_file as database_file


if os.environ.get('SUWAKO_PREFIX'):
    command_prefix = os.environ.get('SUWAKO_PREFIX')
else:
    command_prefix = "-"

initial_extensions = [
    "suwako.cogs.BotManagement",
    "suwako.cogs.MemberManagement",
    "suwako.cogs.MemberInfoSyncing",
    "suwako.cogs.MemberStatistics",
    "suwako.cogs.MemberVerification",
]

intents = discord.Intents.default()
intents.members = True
intents.message_content = True


class Suwako(commands.Bot):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.background_tasks = []

        self.app_version = VERSION
        self.project_contributors = CONTRIBUTORS

        self.description = f"Suwako {self.app_version}"
        self.database_file = database_file
        self.db = None
        self.osu = None

    async def setup_hook(self):
        self.db = await aiosqlite.connect(self.database_file)

        await first_run.ensure_tables(self.db)
        await first_run.add_admins(self)
        await permissions.load_users(self.db)

        self.osu = aioosuapi(osu_api_key)

        for extension in initial_extensions:
            await self.load_extension(extension)

    async def close(self):
        # Cancel all Task object generated by cogs.
        # This prevents any task still running due to having long sleep time.
        for task in self.background_tasks:
            task.cancel()

        # Close osu web api session
        if self.osu:
            await self.osu.close()

        # Close connection to the database
        if self.db:
            await self.db.close()

        # Run actual discord.py close.
        # await super().close()

        # for now let's just quit() since the thing above does not work :c
        quit()

    async def on_ready(self):
        print("Logged in as")
        print(self.user.name)
        print(self.user.id)
        print("------")


client = Suwako(command_prefix=command_prefix, intents=intents)
client.run(bot_token)
